/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedStoryRouteImport } from './routes/_authenticated/story'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPetsRouteImport } from './routes/_authenticated/pets'
import { Route as AuthenticatedLettersRouteImport } from './routes/_authenticated/letters'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedCapsulesRouteImport } from './routes/_authenticated/capsules'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoryRoute = AuthenticatedStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetsRoute = AuthenticatedPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLettersRoute = AuthenticatedLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCapsulesRoute = AuthenticatedCapsulesRouteImport.update({
  id: '/capsules',
  path: '/capsules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/capsules': typeof AuthenticatedCapsulesRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/letters': typeof AuthenticatedLettersRoute
  '/pets': typeof AuthenticatedPetsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/story': typeof AuthenticatedStoryRoute
  '/timeline': typeof AuthenticatedTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/capsules': typeof AuthenticatedCapsulesRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/letters': typeof AuthenticatedLettersRoute
  '/pets': typeof AuthenticatedPetsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/story': typeof AuthenticatedStoryRoute
  '/timeline': typeof AuthenticatedTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/capsules': typeof AuthenticatedCapsulesRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/letters': typeof AuthenticatedLettersRoute
  '/_authenticated/pets': typeof AuthenticatedPetsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/story': typeof AuthenticatedStoryRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/archive'
    | '/calendar'
    | '/capsules'
    | '/gallery'
    | '/home'
    | '/letters'
    | '/pets'
    | '/plans'
    | '/profile'
    | '/search'
    | '/story'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/archive'
    | '/calendar'
    | '/capsules'
    | '/gallery'
    | '/home'
    | '/letters'
    | '/pets'
    | '/plans'
    | '/profile'
    | '/search'
    | '/story'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sitemap.xml'
    | '/_authenticated/archive'
    | '/_authenticated/calendar'
    | '/_authenticated/capsules'
    | '/_authenticated/gallery'
    | '/_authenticated/home'
    | '/_authenticated/letters'
    | '/_authenticated/pets'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/story'
    | '/_authenticated/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story': {
      id: '/_authenticated/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof AuthenticatedStoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pets': {
      id: '/_authenticated/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AuthenticatedPetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/letters': {
      id: '/_authenticated/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof AuthenticatedLettersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capsules': {
      id: '/_authenticated/capsules'
      path: '/capsules'
      fullPath: '/capsules'
      preLoaderRoute: typeof AuthenticatedCapsulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCapsulesRoute: typeof AuthenticatedCapsulesRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLettersRoute: typeof AuthenticatedLettersRoute
  AuthenticatedPetsRoute: typeof AuthenticatedPetsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedStoryRoute: typeof AuthenticatedStoryRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCapsulesRoute: AuthenticatedCapsulesRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLettersRoute: AuthenticatedLettersRoute,
  AuthenticatedPetsRoute: AuthenticatedPetsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedStoryRoute: AuthenticatedStoryRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
